linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # containedctx
    # contextcheck
    # cyclop TODO: Reduce complexity
    - depguard
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    # errname
    - execinquery
    # exhaustive
    # exhaustivestruct
    # exhaustruct
    - exportloopref
    - forbidigo
    # forcetypeassert
    - funlen
    # gci
    # gochecknoglobals
    # gochecknoinits
    - gocognit
    # goconst
    # gocritic
    - gocyclo
    # godot
    # goerr113 TODO: Use errors.Is
    - gofmt
    # gofumpt
    - goheader
    - goimports
    # gomnd TODO: Avoid magic numbers
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    # gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    # nestif TODO: Reduce complexity
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    # nonamedreturns TODO: Avoid namedreturns
    - nosprintfhostport
    # paralleltest
    - prealloc
    # predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    # stylecheck  db/Db instead of DB
    - tagliatelle
    - tenv
    - testableexamples
    # testpackage
    # thelper
    - tparallel
    # typecheck
    - unconvert
    # unparam  TODO: Remove unused params
    - unused
    - usestdlibvars
    # whitespace
    # wrapcheck
    # wsl
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: false

linters-settings:
  funlen:
    lines: 120
    statements: 120
  goconst:
    min-len: 3
    min-occurrences: 2
  lll:
    line-length: 180
    tab-width: 1
  misspell:
    locale: US
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: line-length-limit
        severity: error
        arguments: [330]

issues:
  exclude-rules:
    - linters:
        - funlen
      source: "^func Test"
