// Copyright 2023 VMware, Inc.
// Licensed to VMware, Inc. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. VMware, Inc. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by "stringer -type=Status realization_store/status.go"; DO NOT EDIT.

package realization_store

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[DELETION_REALIZED-100]
	_ = x[REALIZED-200]
	_ = x[DELETION_IN_PROGRESS-300]
	_ = x[DELETION_PENDING-400]
	_ = x[IN_PROGRESS-600]
	_ = x[PENDING-800]
	_ = x[ERROR-1000]
}

const (
	_Status_name_0 = "UNKNOWN"
	_Status_name_1 = "DELETION_REALIZED"
	_Status_name_2 = "REALIZED"
	_Status_name_3 = "DELETION_IN_PROGRESS"
	_Status_name_4 = "DELETION_PENDING"
	_Status_name_5 = "IN_PROGRESS"
	_Status_name_6 = "PENDING"
	_Status_name_7 = "ERROR"
)

func (i Status) String() string {
	switch {
	case i == 0:
		return _Status_name_0
	case i == 100:
		return _Status_name_1
	case i == 200:
		return _Status_name_2
	case i == 300:
		return _Status_name_3
	case i == 400:
		return _Status_name_4
	case i == 600:
		return _Status_name_5
	case i == 800:
		return _Status_name_6
	case i == 1000:
		return _Status_name_7
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
