---
name: Daily
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'trace'
jobs:
  test:
    name: Unit test
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21', '1.22']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go using version for latest ${{ matrix.go }} version
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: Run unit tests
        run: |
          mkdir -p $(go env GOPATH)
          mkdir -p $(go env GOCACHE)
          sudo make test benchmarks
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/coverage.out
          flags: unit-tests
          name: codecov-unit-test
  lint:
    name: Check lint
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21', '1.22']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go using version for latest ${{ matrix.go }} version
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: Run lint
        run: |
          mkdir -p $(go env GOPATH)
          mkdir -p $(go env GOCACHE)
          make lint mlint
