---
name: Go
on:
  pull_request:
    branches:
      - main
      - release-*
      - feature/*
  push:
    branches:
      - main
      - release-*
      - feature/*
  workflow_run:
    workflows: ["Build"]
    types:
      - complete

jobs:
  test:
    name: Unit test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go using version for latest 1.19 version
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true

      - name: Run unit tests
        run: |
          mkdir -p $(go env GOPATH)
          mkdir -p $(go env GOCACHE)
          sudo make test
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/coverage.out
          flags: unit-tests
          name: codecov-unit-test

  lint:
    name: Check lint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go using version for latest 1.19 version
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true
      - name: Run lint
        run: |
          mkdir -p $(go env GOPATH)
          mkdir -p $(go env GOCACHE)
          make lint
