---
name: Go
on:
  pull_request:
    branches:
      - main
      - release-*
      - feature/*
  push:
    branches:
      - main
      - release-*
      - feature/*
  workflow_run:
    workflows: ["Build"]
    types:
      - complete
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  test:
    name: Unit test
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go using version for latest ${{ matrix.go }} version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: Run unit tests
        run: |
          mkdir -p $(go env GOPATH)
          mkdir -p $(go env GOCACHE)
          sudo make test
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/coverage.out
          flags: unit-tests
          name: codecov-unit-test
  lint:
    name: Check lint
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go using version for latest ${{ matrix.go }} version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: Run lint
        run: |
          mkdir -p $(go env GOPATH)
          mkdir -p $(go env GOCACHE)
          make lint
